# Generated by Django 6.0.3 on 2026-03-19 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=100)),
                ('employees', models.IntegerField(blank=True, choices=[(1, 'Just me'), (2, '2 - 10'), (11, '11 - 50'), (51, '51 - 500'), (501, '500+')], help_text='How many people work at your company?', max_length=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='company_logo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
