# Generated by Django 6.0.3 on 2026-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employees',
            field=models.IntegerField(blank=True, choices=[(1, 'Just me'), (2, '2 - 10'), (11, '11 - 50'), (51, '51 - 500'), (501, '500+')], help_text='How many people work at your company?', null=True),
        ),
    ]
